NurseryEcom/BasicNavs/urls.py
from django.urls import path
from . import views 

app_name = 'BasicNavs'
urlpatterns = [
    path('', views.home, name='home'),
    path('aboutUs', views.aboutUs, name='aboutUs'),
    path('contactUs', views.contactUs, name='contactUs')
]

NurseryEcom/CustomerLogin/urls.py
from django.urls import path
from . import views 

app_name = 'CustomerLogin'
urlpatterns = [
    path('register', views.register, name='customerRegister'),
    path('dashboard', views.dashboard, name ='customerDashboard'),
    path('login', views.login, name='customerLogin'),
    path('logout', views.logout_request, name='customerLogout')
  
]

NurseryEcom/NurseryEcom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("BasicNavs.urls")),
    path('customer/', include("CustomerLogin.urls")),
    path('shop/', include('Shop.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

NurseryEcom/Shop/urls.py
from django.urls import path
from . import views 

app_name = 'Shop'
urlpatterns = [
    path('', views.index, name='shopIndex'),
    path('view/<slug:category>', views.filter, name='filter'),
    path('add_to_cart/<int:id>/', views.add_to_cart, name='add_to_cart'),
    path('cartDisplay', views.display_cart, name='display_cart'),
    path('updateCart', views.update_cart, name='update_cart'),
    path('deleteCart', views.delete_cart, name='delete_cart'),
    path('search', views.search, name= 'search_product')
]

NurseryEcom/CustomerLogin/models.py
from django.db import models

# Create your models here.

NurseryEcom/Shop/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
categoryChoice = (
    ('IN', "Indoor"),
    ('OUT', "Outdoor"),
    ('SUC', "Saculent"),
    ('SE', "Seasonal"),
    ('OTH',"Others")
)
status = (
    ('NP', "Not Paid"), 
    ('HP', "Half Paid"),
    ('FP', "Full Paid"),
    ("SHIP", "Shipped")
)
class Product(models.Model):
    product_name = models.CharField( max_length=50)
    price = models.IntegerField()
    category = models.CharField(max_length = 3 , choices = categoryChoice)
    description = models.TextField(max_length = 500)
    image = models.ImageField(upload_to = 'images/')

    def __str__(self):
        return self.product_name

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    num = models.IntegerField()
    status = models.CharField(max_length = 4, choices = status)

    def __str__(self):
        return self.product.product_name + " ordered by " + self.user.username

NurseryEcom/BasicNavs/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'BasicNavs/home.html')

def aboutUs(request):
    return render(request, 'BasicNavs/aboutUs.html')

def contactUs(request):
    return render(request, 'BasicNavs/contactUs.html')

NurseryEcom/CustomerLogin/views.py
from django.shortcuts import render, redirect
from .registerForm import NewUserForm
from django.contrib.auth import login as auth_login

from django.contrib.auth import authenticate,logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

#Register New User
def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if(form.is_valid()):
            user = form.save()
            auth_login(request, user)
            messages.success(request, "Regestration Successful")
            return redirect("CustomerLogin:customerDashboard")
        messages.error(request, "Unsuccessful regestration. Invalid Information.")
    form = NewUserForm()
    return render(request, 'CustomerLogin/register.html',{'register_form':form})
# Login View
def login(request):
    if(request.method=='POST'):
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username = username, password = password)
            if user is not None:
                auth_login(request, user)
                #messages.info(request, f'Your are now logged in {username}.')
                return redirect("CustomerLogin:customerDashboard")
            else:
                messages.error(request, "Invalid  username of password")
        else:
            messages.error(request, "Invalid username or password")
    form = AuthenticationForm()
    return render(request, 'CustomerLogin/login.html',{"login_form":form})
# Logout
def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("CustomerLogin:customerLogin")

# Dashboard view 
def dashboard(request):
    if not request.user.is_authenticated:
        return redirect("CustomerLogin:customerLogin")
    else:
        return render(request, 'CustomerLogin/dashboard.html')

NurseryEcom/Shop/views.py
from django.shortcuts import render,redirect
from .models import Product
from .cart import Cart
from .product import productClass
# Create your views here.

def index(request):
    cart = Cart(request)
    totalPrice = cart.totalPrice()
    product = productClass()
    products = product.getProduct()
    return render(request, 'Shop/shop.html',{"products": products,"totalPrice":totalPrice,'fromIndex':True})

def filter(request, category):
    cart = Cart(request)
    totalPrice = cart.totalPrice()
    product = productClass()
    products = product.filterProduct(category)
    return render(request, 'Shop/shop.html',{"products": products,"totalPrice":totalPrice,'fromIndex':False})

def search(request):
    if request.method == "POST":
        productKeyword = request.POST['keyword']
        cart = Cart(request)
        totalPrice = cart.totalPrice()
        product = productClass()
        products = product.searchProduct(productKeyword)
        return render(request, 'Shop/shop.html',{"products": products,"totalPrice":totalPrice,'fromIndex':False})


def add_to_cart(request, id):
    if request.method == 'POST':
        if request.POST['fromIndex']:
            print("From Index")
        else:
            print("Not from Index")
        product = Product.objects.get(id=id)
        cart = Cart(request)
        quantity = request.POST['quantity']
        if not quantity:
            quantity = 1
        cart.add(product, quantity)
        print(product.category)
        
        if request.POST['fromIndex'] == 'True/':
            print("From the index")
            return redirect("Shop:shopIndex")
        else:
            print("Not from the index")
            return redirect("Shop:filter", category=product.category)
        
    
def display_cart(request):
    cart = Cart(request)
    cartProducts = cart.list()
    totalPrice = cart.totalPrice()
    return render(request,'Shop/cartDisplay.html',{"cartProducts":cartProducts, "totalPrice":totalPrice})

def update_cart(request):
    if request.method == "POST":
        quantity = request.POST["updateQuantity"]
        id = request.POST["id"]
        cart = Cart(request)
        cart.update(id, quantity)
        return redirect("Shop:display_cart")
def delete_cart(request):
   if(request.method == "POST"):
       id = request.POST['id']
       cart = Cart(request)
       cart.delete(id)
       return redirect("Shop:display_cart")

        

NurseryEcom/BasicNavs/templates/BasicNavs/aboutUs.html
{% extends 'BasicNavs/partials/header.html' %}
{% load static %}
{%block CSJSS %}
    <link rel="stylesheet" href={% static 'BasicNavs/css/aboutUs.css' %}>
{% endblock %}

{% block MAIN %}

    <h1>About Us</h1>

{% endblock %}

NurseryEcom/BasicNavs/templates/BasicNavs/contactUs.html
{% extends 'BasicNavs/partials/header.html' %}
{%load static%}
{%block CSJSS %}
    <link rel="stylesheet" href={% static 'BasicNavs/css/contactUs.css' %}>
{% endblock %}

{% block MAIN %}

    <h1>Contact Us</h1>

{% endblock %}

NurseryEcom/BasicNavs/templates/BasicNavs/home.html
{% extends 'BasicNavs/partials/header.html' %}
{% load static %}
{%block CSJSS %}
    <link rel="stylesheet" href={% static 'BasicNavs/css/home.css' %}>
{% endblock %}

{% block MAIN %}

    <h1>Homepage</h1>

{% endblock %}

NurseryEcom/BasicNavs/templates/BasicNavs/partials/header.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static 'BasicNavs/css/header.css' %}>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% block CSJSS %}
    {% endblock %}
    <title>Ghimire Nursery</title>
</head>
<body>
    <div class="main">
    {% block MAIN%}

    {% endblock %}
    </div>
</body>
</html>

NurseryEcom/CustomerLogin/templates/CustomerLogin/dashboard.html
{% extends 'BasicNavs/partials/header.html' %}
{% load static %}

{% block CSJSS %}
{%endblock%}

{%block MAIN%}
    <p>This is dashboard</p>
     <a class="nav-link" href="{%url 'CustomerLogin:customerLogout'%}">Logout</a>
{%endblock%}

NurseryEcom/CustomerLogin/templates/CustomerLogin/login.html
{% extends 'BasicNavs/partials/header.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block CSJSS %}
    <link rel="stylesheet" href={%static 'CustomerLogin/css/login.css' %}>
{%endblock%}

{%block MAIN%}
    <h1 class='text-center'>Login</h1>
    <form method = "POST" class='jumbotron'>
        {%csrf_token%}
    
        {{login_form | crispy}}
        <br>
        <button class="btn btn-primary" type="submit">Login</button>
    </form>
    <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
{%endblock%}

NurseryEcom/CustomerLogin/templates/CustomerLogin/register.html
{% extends 'BasicNavs/partials/header.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block CSJSS %}
    <link rel="stylesheet" href={%static 'CustomerLogin/css/register.css' %}>
{%endblock%}
{%block MAIN%}
<h1 class='text-center'>Register</h1>
<form action="" method="POST" class='jumbotron'>
    {% csrf_token %}
    {{register_form | crispy}}
    <button class="btn btn-primary" type="submit">Register</button>
</form>
{%endblock%}

NurseryEcom/Shop/templates/Shop/cartDisplay.html
{% extends 'BasicNavs/partials/header.html' %}
{%load static%}

{%block CSJSS %}

{% endblock %}

{% block MAIN %}
<div class="container">
    <h2>Cart</h2>
    <p>Cart Details:</p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product Name</th>
                <th>Quantity</th>
                <th>Per Unit Price</th>
                <th>Total Price</th>
            </tr>
        </thead>
        <tbody>
            {%if totalPrice == 0 %}
                <tr>
                    <td colspan="5" class="text-center">No Items Found</td>
                </tr>
            {%else%}
            {%for product in cartProducts%}
            <tr>
                <td><img src="{{product.image}}" alt="image of plant" height="40px" width="40px"></td>
                <td>{{product.product_name}}</td>
                <td>
                    <form action="{%url 'Shop:update_cart'%}" method = "POST">
                        {% csrf_token %}
                        <input type="text" name="updateQuantity" value="{{product.quantity}}"><button>Update</button>
                        <input type="hidden" value={{product.id}} name='id'>
                    </form>
                </td>
                <td>{{product.price}}</td>
                <td>{{product.total}}</td>
                <td>
                    <form action="{%url 'Shop:delete_cart'%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value={{product.id}} name='id'>
                        <button type='submit'>Delete</button>
                    </form>
                </td>
            </tr>
            {%endfor%}
            <tr>
                <td colspan="4" class='text-right Strong'>Total</td>
                <td>{{totalPrice}}</td>
                
            </tr>
            {% endif %}
        </tbody>
    </table>
    <a href="{%url 'Shop:shopIndex'%}">Continue Shopping</a>
</div>


{% endblock %}

NurseryEcom/Shop/templates/Shop/shop.html
{% extends 'BasicNavs/partials/header.html' %}
{%load static%}

{%block CSJSS %}
    <link rel="stylesheet" href={% static 'Shop/css/shop.css' %}>
{% endblock %}

{% block MAIN %}
    
    <h1>Shop Page</h1>
    <form action="{%url 'Shop:search_product'%}" method="POST">
        {%csrf_token%}
        <input type="text" name='keyword'>
        <input type="submit">
    </form>
    <h6> <a href="{%url 'Shop:display_cart'%}"> Cart Total Rs. {{totalPrice}}</a></h6>
    <div class='buttonlist'>
        <a href="{%url 'Shop:shopIndex'%}">All Product</a>
        <a href="/shop/view/OUT">Outdoor</a>
        <a href="/shop/view/IN">Indoor</a>
        <a href="/shop/view/SUC">Saculent</a>
        <a href="/shop/view/SE">Seasonal</a>
        <a href="/shop/view/OTH">Others</a>
        
    </div>
    {%for product in products%}
        <div class="product-catalog">
            <h4>{{product.product_name}}</h4>
            <img src="{{product.image}}"/>
            <h6>Price: Rs.{{product.price}} per unit</h6>
            <p>Category {{product.category}}</p>
            <form action="{% url 'Shop:add_to_cart' product.id %}" method="POST">
                {%csrf_token%}
                <input type="number" name='quantity' placeholder="1">
                <input type=hidden name="fromIndex" value={{fromIndex}}/>
                <button class='btn btn-primary btn-sm' type='submit'>Add to cart</button>
            </form>
        </div>
    {%endfor%}

{% endblock %}